<a href="https://colab.research.google.com/github/simichakravarty16/ds2002-fa26/blob/main/notebooks/04-json-apis/2026-10-09%20%E2%80%94%20Public%20API%20to%20Clean%20Table%20%E2%80%94%20Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Public API to Clean Table

**Lab — 2026-10-09 · Fall 2026**
**Name:** Simi Chakravarty

---

## Lab 07 — Public API to Clean Table

Build the weather-ingestion function you will actually reuse on the midterm. It has to pull real data, survive a flaky network, say plainly when it fell back to sample data, and hand back a table that is safe to join.

The last requirement is the one people skip. A function that returns *something* no matter what is worse than one that fails loudly, because the failure ends up in your findings instead of your console.

### Part 1 — a fetch you can trust

**TODO:** finish `get_weather`. Requirements:

- sets a timeout
- retries on 429 and 5xx with an increasing delay
- raises immediately on 400 or 404 — those are your bug, not theirs
- returns a DataFrame from the `daily` block

You wrote this shape in Wednesday's studio. Rebuild it from memory if you can.

In [1]:
import requests, pandas as pd, time

BASE = 'https://archive-api.open-meteo.com/v1/archive'
RETRY_STATUSES = {429, 500, 502, 503, 504}

def get_weather(start, end, lat=38.03, lon=-78.51, tries=3):
    """Daily max temperature and total precipitation for a date range."""
    params = {
        'latitude': lat, 'longitude': lon,
        'start_date': start, 'end_date': end,
        'daily': 'temperature_2m_max,precipitation_sum',
        'timezone': 'America/New_York',
    }
    for attempt in range(tries):
        try:
            r = requests.get(BASE, params=params, timeout=10)
        except requests.RequestException:
            if attempt == tries - 1:
                raise
        else:
            if r.status_code in (400, 404):
                r.raise_for_status()

            if r.status_code == 200:
                return pd.DataFrame(r.json()['daily'])

            if r.status_code not in RETRY_STATUSES:
                r.raise_for_status()
                raise requests.HTTPError(
                    f"Unexpected status code: {r.status_code}"
                )

            if attempt == tries - 1:
                r.raise_for_status()

        if attempt < tries - 1:
            delay = 0.5 * (2 ** attempt)
            time.sleep(delay)

    raise RuntimeError("Weather request failed after every attempt")

**In this part, I needed to expand the get weather function in order to set a timeout, retry on the errors in RETRY_STATUSES with an increasing delay, raises immediately on 400 or 404, and returns a dataframe from the daily block. First, I needed to use for attempt in range(tries) to specify that the computer should try to get the information a defined amount of times (this would be defined as an argument in the get_weather function). Next, I made the request and set a timeout using try: r = requests.get(BASE, params=params, timeout=10). This essentially tells the computer to access the URL in BASE, get the defined params (latitude, start_date, etc.), and let the request wait up to 10 seconds for the server to respond before raising a timeout exception. I also needed to account for if the computer is completely unable to access the URL, so I used the code within the except block. This code checks whether the request was the final attempt and, if so, tells the computer to stop and report the error. If it is not the final time (tries - 1), the computer can wait and try to access the URL again. The else block defines what to do when the website responds. If the request is wrong and the website sends a 400 (invalid request) or 404 (requested resource not found), then the code will immediately raise an error to report the user to fix the mistake, rather than continue with more tries. Next, the code accounts for if the website succeeds in pulling the data (200) and returns a dataframe by reading the JSON and selecting for the section containing daily weather information. If the website has some kinds of problem outside of RETRY_STATUSES, the next if statement will raise an error that showcases the Unexpected status code. If there is any other type of status code produced, it now must be one that is present in RETRY_STATUSES. The next if statement checks whether the computer has used its final attempt, and raise an error on the final attempt so it does not loop forever. To make sure that there is an increasing delay, I used the next if statement to make sure that every subsequent attempt takes longer. This makes sure that if the website is overloaded, the computer does not immediately keep requesting from it. If none of these work still, the final backup raises an error that states, "Weather request failed after every attempt."**

### Part 2 — two home weekends

Pull weather for **2026-09-05** and **2026-10-03**. One range covering both is fine and is one request instead of two — be nice to free APIs.

If the call genuinely fails, use the fallback in Part 3, but you must record that you did.

In [2]:
weather = get_weather(start = '2026-09-05', end = '2026-10-03')
used_fallback = False

weather_dates = weather[weather['time'].isin(['2026-09-05', '2026-10-03'])].copy()
weather_dates.head()

          time  temperature_2m_max  precipitation_sum
0   2026-09-05                29.4                2.5
28  2026-10-03                22.0               14.7

**First, I used the get_weather() function that I designed in the previous part to retrieve the entire specified date range (2026-09-05 - 2026-10-03) from the weather URL. This call succeeded without any errors, so I did not use the fallback and set used_fallback = FALSE. Next, I wanted to filter the dataframe to only get the requested dates, so I made sure that the time column was either 2026-09-05 or 2026-10-03 and copied the original dataframe. Finally, I used the .head() method to take a look at the dataframe and make sure there were no mistakes.**

### Part 3 — the fallback, labelled as a fallback

Sample values so the notebook still runs without a network. The important part is the `source` column: whoever reads your results can tell which rows are real.

In [3]:
FALLBACK = pd.DataFrame({
    'time': ['2026-09-05', '2026-10-03'],
    'temperature_2m_max': [30.1, 18.4],
    'precipitation_sum': [0.0, 22.5],
})

used_fallback = False

if used_fallback:
    wx = FALLBACK.copy()
    wx['source'] = 'fallback sample'
else:
    wx = weather_dates.copy()
    wx['source'] = 'open-meteo'

wx

          time  temperature_2m_max  precipitation_sum      source
0   2026-09-05                29.4                2.5  open-meteo
28  2026-10-03                22.0               14.7  open-meteo

**Since I did not need to use the fallback in Part 2, I set used_fallback = False. If an alternative user had a problem accessing the weather URL, they could set used_fallback = True. If used_fallback is equal to True, this code chooses to copy the sample data (FALLBACK) and create a source column that shows where the data came from. If used_fallback is equal to False, the else block copies the actual API results from weather_dates into wx and defines the source as open-mateo. This is so whoever reads the results can tell which rows are real. Finally, I took a look at the wx dataframe to make sure everything had run correctly.**

### Part 4 — make it joinable

**TODO:** produce a frame with a real datetime column named `date`, plus `temp_max`, `precip_mm`, and `source`. Rename the API's column names to yours — your pipeline should not inherit somebody else's naming.

In [4]:
wx = wx.rename(columns={
    'time': 'date',
    'temperature_2m_max': 'temp_max',
    'precipitation_sum': 'precip_mm'
})

wx['date'] = pd.to_datetime(wx['date'])

wx

         date  temp_max  precip_mm      source
0  2026-09-05      29.4        2.5  open-meteo
28 2026-10-03      22.0       14.7  open-meteo

**First, I worked off of my existing wx dataframe and renames the columns to match the names designated in the TODO. I also converted the date column to datetime so it would be easier to work off of in the future. Finally, I displayed the final dataframe.**

### Part 5 — validate before you use it

This is the habit that separates a pipeline from a script. State what must be true, and find out here rather than three cells later inside a join.

**TODO:** uncomment and make them pass.

In [5]:
assert list(wx.columns) == ['date', 'temp_max', 'precip_mm', 'source']
assert len(wx) == 2, f'expected 2 rows, got {len(wx)}'
assert pd.api.types.is_datetime64_any_dtype(wx['date'])
assert wx['precip_mm'].notna().all(), 'missing precipitation'
assert (wx['precip_mm'] >= 0).all(), 'negative rainfall is not a thing'
print('weather table is safe to join.')

weather table is safe to join.

**I uncommented each of these assertions and they all happened to pass with my first time writing out the code.**

### Part 6 — answer the question

**TODO:** which of the two dates was wetter, and by how much? Print a sentence a vendor could read, not just a number.

In [6]:
wetter = wx.loc[wx['precip_mm'].idxmax()]
drier = wx.loc[wx['precip_mm'].idxmin()]

difference = wetter['precip_mm'] - drier['precip_mm']

print(
    f"{wetter['date'].strftime('%B %d, %Y')} was wetter, "
    f"with {difference:.1f} mm more precipitation than "
    f"{drier['date'].strftime('%B %d, %Y')}."
)

October 03, 2026 was wetter, with 12.2 mm more precipitation than September 05, 2026.

**To find the row with the highest precipitation, I used the .idxmax() method on the precip_mm column in wx, making sure to use .loc so that I could reference the wx files by name. I did a similar thing to find the drier column, but instead used the .idxmin() method. Next, I found the difference by subtracting the precipitation of the drier row from the precipitation of the wetter row. Finally, I printed a sentence to state that October 03, 2026 was wetter by 12.2mm of precipitation.**

### Part 7 — cite it

**TODO:** print the endpoint, the coordinates, the date range, when you pulled it, and whether the data is real or fallback.

In [7]:
print(f"Endpoint: {BASE}")
print(f"Coordinates: latitude={38.03}, longitude={-78.51}")
print(f"Date range: 2026-09-05 to 2026-10-03")
print(f"Pulled at: {pd.Timestamp.now()}")
print(f"Data source: {'Fallback sample data' if used_fallback else 'Real Open-Meteo API data'}")

Endpoint: https://archive-api.open-meteo.com/v1/archive
Coordinates: latitude=38.03, longitude=-78.51
Date range: 2026-09-05 to 2026-10-03
Pulled at: 2026-10-11 16:26:44.488022
Data source: Real Open-Meteo API data

**To print all of these details, I first started with the endpoint, which would be BASE (the API endpoint URL). Next, the coordinates were defined in part 1, so I used the latitude and longitude which had been requested. Since the date range needed was provided to us, I added this in. To show when I pulled it, I recorded the current date and time using pd.Timestamp.now() as it would have been pulled when all of this code has been fun. Finally, I provided the data source conditionally, making sure to check whether used_fallback was True and the data was the fallback sample data or whether it was open-mateo API data.**

### Write-up

Suppose `get_weather` returned an empty DataFrame on failure instead of raising. Walk through what happens next: you merge it onto 200 days of sales and chart rain against revenue. What does the chart show, and why would nobody catch it?

*If get_weather returns an empty DataFrame on failure, the program would continue to run like if the request had completed successfully. If you were to then merge it onto 200 days of sales, the weather columns would remain blank for every date. The chart would be blank or perhaps solely chart the revenue data because there is no rain data for it to pull from. Since the code doesn't raise an error at the beginning, no one is able to catch the mistake and the merge is still able to succeed, even though all of the weather columns are null. This shows how a small mistake at the beginning has large downstream effect and why it is important to provide conditions for errors to raise in different scenarios.*

### Stretch

Pull the same two dates for a second location — Orlando is at roughly `28.54, -81.38` — and put both cities in one long-format frame with a `city` column. That is the exact shape the midterm needs when you compare stores in different places.

In [8]:
charlottesville = get_weather(start = '2026-09-05', end = '2026-10-03', lat = 38.03, lon = -78.51)
orlando = get_weather(start = '2026-09-05', end = '2026-10-03', lat = 28.54, lon = -81.38)

dates = ['2026-09-05', '2026-10-03']



charlottesville_dates = charlottesville[
    charlottesville['time'].isin(dates)
].copy()
orlando_dates = orlando[
    orlando['time'].isin(dates)
].copy()



charlottesville_dates['city'] = 'Charlottesville'
orlando_dates['city'] = 'Orlando'



weather_cities = pd.concat(
    [charlottesville_dates, orlando_dates],
    ignore_index=True
)
weather_cities.head()

         time  temperature_2m_max  precipitation_sum             city
0  2026-09-05                29.4                2.5  Charlottesville
1  2026-10-03                22.0               14.7  Charlottesville
2  2026-09-05                32.1                3.9          Orlando
3  2026-10-03                30.4               14.5          Orlando

**First, I used the previously defined get_weather() function to pull weather data for both Charlottesville and Orlando on this date range, making them both functional dataframes. To specify the dates, I defined dates = ['2026-09-05', '2026-10-03'] and filtered the Charlottesville and Orlando dataframes to only include dates in this list. I made sure to make a copy of the original data while doing this. To create the city column, I defined all of the rows in the Charlottesville column to be Charlottesville and vice versa with the Orlando dataframe. Finally, I needed to combine both cities into one dataframe, which I did using the pd.concat() function. I set the ignore_index argument to True so a new row index would be created instead of keeping the original indices.**